services:
  rhyme-mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./Docker-DB:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3001:3306"
    networks:
      - rhymenet
  
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    networks:
      - rhymenet
    depends_on:
      - rhyme-mysql

networks:
  rhymenet:
    driver: bridge